# apiVersion: v1
# kind: Service
# metadata:
#   name: reddit-service
# spec:
#   selector:
#     app: reddit-app
#   ports:
#   - port: 8000
#     targetPort: 8000
#     nodePort: 30001  
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  type: LoadBalancer
  selector:
    app: reddit-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000